version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - WALLETCONNECT_PROJECT_ID=${WALLETCONNECT_PROJECT_ID}
      - RPC_URL=${RPC_URL}
      - DATABASE_URL=/app/data/giggle.db
    volumes:
      - giggle-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - AGENT_PORT=3001
    restart: unless-stopped

volumes:
  giggle-data:
